name: hannbyul

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Dependency
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run python file
        run: |
          python README.py
      - name: Add & Commit
        uses: EndBug/add-and-commit@v4.4.0
        with:
          add: "README.md"
          message: "$(date +'%Y-%m-%d')"
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
